apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    owner: RamanMarkau
spec:
  selector:
    app: {{ .Release.Name }}-tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
