apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - romanmarkov.org
      secretName: romanmarkov-tls
  rules:
    - host: romanmarkov.org
      http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.spec.ServiceName1 }}
                port:
                  number: 80
          - path: /app2
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.spec.ServiceName2 }}
                port:
                  number: 8080
          - path: /port5000
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.spec.ServiceName2 }}
                port:
                  number: 5000
          - path: /port6000
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.spec.ServiceName2 }}
                port:
                  number: 6000
