apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  labels:
    owner: RamanMarkau
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  