apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-tomcat
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tomcat
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tomcat
    spec:
      containers:
      - name: {{ .Release.Name }}-tomcat
        image: {{ .Values.container.image }}
        ports:
        - containerPort: 8080
        env:
        - name: TOMCAT_USERNAME
          value: "admin" 
        - name: TOMCAT_PASSWORD
          value: "admin123" 
        - name: ALLOW_EMPTY_PASSWORD
          value: "no" 
        - name: NAMI_LOG_LEVEL
          value: "INFO"
        - name: BITNAMI_DEBUG
          value: "false"
