apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    owner: RamanMarkau
spec:
  selector:
    app: {{ .Release.Name }}-tomcat
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: custom
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: custom2
      protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP

